// src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { DataService } from './data.service';
import config from 'devextreme/core/config';
import { DxDataGridComponent } from 'devextreme-angular';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  providers: [DataService],
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  dataSource: any;
  states: any;
  rowKey: any;
  @ViewChild(DxDataGridComponent) dataGrid: DxDataGridComponent;
  constructor(service: DataService) {
    config({
      editorStylingMode: 'filled'
    });
    this.dataSource = service.getEmployees();
    this.states = service.getStates();
  }
  customizeItem = (item) => {

    if (item && item.itemType === "group" && item.caption === "Home Address") {
      let index = this.dataGrid.instance.getRowIndexByKey(this.rowKey) || 0;
      let isVisible = this.dataGrid.instance.cellValue(index, "AddressRequired");
      item.visible = isVisible;
    }
  }
  onEditorPreparing(e) {
    if (e.dataField === "LastName" && e.parentType === "dataRow") {
      e.editorOptions.disabled = e.row.data && e.row.data.FirstName === "";
    }
  }
  onEditingStart(e) {
    this.rowKey = e.key;
  }
  onInitNewRow(e) {
    e.data.AddressRequired = false;
    e.data.FirstName = "";
  }
  setCellValue(newData, value) {
    let column = (<any>this);
    column.defaultSetCellValue(newData, value)
  }
}

<dx-data-grid (onEditorPreparing)="onEditorPreparing($event)" (onEditingStart)="onEditingStart($event)"
  (onInitNewRow)="onInitNewRow($event)" [dataSource]="dataSource" keyExpr="ID" [showBorders]="true">
  <dxo-paging [enabled]="false"></dxo-paging>
  <dxo-editing mode="popup" [allowAdding]="true" [allowUpdating]="true">
    <dxo-popup title="Employee Info" [showTitle]="true" [width]="700" [height]="725"
      [position]="{ my: 'top', at: 'top', of: window }">
    </dxo-popup>
    <dxo-form [customizeItem]="customizeItem">
      <dxi-item itemType="group" [colCount]="2" [colSpan]="2">
        <dxi-item dataField="FirstName"></dxi-item>
        <dxi-item dataField="LastName"></dxi-item>
        <dxi-item dataField="Prefix"></dxi-item>
        <dxi-item dataField="BirthDate"></dxi-item>
        <dxi-item dataField="Position"></dxi-item>
        <dxi-item dataField="HireDate"></dxi-item>
        <dxi-item dataField="Notes" editorType="dxTextArea" [colSpan]="2" [editorOptions]="{ height: 100 }">
        </dxi-item>
        <dxi-item dataField="HireDate"></dxi-item>
      </dxi-item>
      <dxi-item dataField="AddressRequired" [colSpan]="2"></dxi-item>
      <dxi-item itemType="group" caption="Home Address" [colCount]="2" [colSpan]="2">
        <dxi-item dataField="StateID"></dxi-item>
        <dxi-item dataField="Address"></dxi-item>
      </dxi-item>
    </dxo-form>
  </dxo-editing>
  <dxi-column dataField="Prefix" caption="Title" [width]="70"></dxi-column>
  <dxi-column dataField="FirstName" [setCellValue]="setCellValue"></dxi-column>
  <dxi-column dataField="LastName"></dxi-column>
  <dxi-column dataField="BirthDate" dataType="date">
  </dxi-column>
  <dxi-column dataField="Position" [width]="170">
  </dxi-column>
  <dxi-column dataField="HireDate" dataType="date">
  </dxi-column>
  <dxi-column dataField="StateID" caption="State" [width]="125">
    <dxo-lookup [dataSource]="states" displayExpr="Name" valueExpr="ID">
    </dxo-lookup>
  </dxi-column>
  <dxi-column dataField="Address" [visible]="false">
  </dxi-column>
  <dxi-column dataField="Notes" [visible]="false">
  </dxi-column>
  <dxi-column dataField="AddressRequired" [setCellValue]="setCellValue" [visible]="false"></dxi-column>
</dx-data-grid>

// React/src/App.js
import React from 'react';
import './App.css';

import service from './data';
import 'devextreme/dist/css/dx.common.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import config from 'devextreme/core/config';
import 'devextreme-react/text-area';

import DataGrid, { 
  Column,
  Lookup,
  Form,
  Popup,
  Paging,
  Editing
} from 'devextreme-react/data-grid';
import { SimpleItem, GroupItem } from 'devextreme-react/form';

class App extends React.Component {
  constructor(props) {
    super(props);
    config({
      editorStylingMode: 'filled'
    });
    this.dataSource = service.getEmployees();
    this.states = service.getStates();
    this.rowKey = -1;
    this.dataGrid = React.createRef();
    this.popupPosition = { my: 'top', at: 'top', of: window };
    this.editorOptions = { height: 100 };
  }
  render() {
    return (
      <div className="App">
        <DataGrid ref={this.dataGrid} onEditorPreparing={this.onEditorPreparing} onEditingStart={this.onEditingStart}
          onInitNewRow={this.onInitNewRow} dataSource={this.dataSource} keyExpr={"ID"} showBorders={true}>
          <Paging enabled={false} />
          <Editing mode={"popup"} allowAdding={true} allowUpdating={true}>
            <Popup title={"Employee Info"} showTitle={true} width={700} height={725}
              position={this.popupPosition}>
            </Popup>
            <Form customizeItem={this.customizeItem}>
              <GroupItem colCount={2} colSpan={2}>
                <SimpleItem dataField={"FirstName"} />
                <SimpleItem dataField={"LastName"} />
                <SimpleItem dataField={"Prefix"} />
                <SimpleItem dataField={"BirthDate"} />
                <SimpleItem dataField={"Position"} />
                <SimpleItem dataField={"HireDate"} />
                <SimpleItem dataField="Notes" editorType={"dxTextArea"} colSpan={2} editorOptions={this.editorOptions} />
              </GroupItem>
              <SimpleItem dataField={"AddressRequired"} colSpan={2} />
              <GroupItem caption={"Home Address"} colCount={2} colSpan={2}>
                <SimpleItem dataField={"StateID"} />
                <SimpleItem dataField={"Address"} />
              </GroupItem>
            </Form>
          </Editing>
          <Column dataField={"Prefix"} caption={"Title"} width={70} />
          <Column dataField={"FirstName"} setCellValue={this.setCellValue} />
          <Column dataField={"LastName"} />
          <Column dataField={"BirthDate"} dataType={"date"} />
          <Column dataField={"Position"} width={170} />
          <Column dataField={"HireDate"} dataType={"date"} />
          <Column dataField={"StateID"} caption={"State"} width={125}>
            <Lookup dataSource={this.states} displayExpr={"Name"} valueExpr={"ID"}>
            </Lookup>
          </Column>
          <Column dataField={"Address"} visible={false} />
          <Column dataField={"Notes"} visible={false} />
          <Column dataField={"AddressRequired"} setCellValue={this.setCellValue} visible={false} />
        </DataGrid>
      </div>
    );
  }
  customizeItem = (item) => {
    if (item && item.itemType === "group" && item.caption === "Home Address") {
      let gridInstance = this.dataGrid.current.instance;
      let index = gridInstance.getRowIndexByKey(this.rowKey);
      index = index === -1 ? 0 : index ;
      let isVisible = gridInstance.cellValue(index, "AddressRequired");
      item.visible = isVisible;
    }
  }
  onEditorPreparing = (e) => {
    if (e.dataField === "LastName" && e.parentType === "dataRow") {
      e.editorOptions.disabled = e.row.data && e.row.data.FirstName === "";
    }
  }
  onEditingStart = (e) => {
    this.rowKey = e.key;
  }
  onInitNewRow = (e) => {
    this.rowKey = -1;
    e.data.AddressRequired = false;
    e.data.FirstName = "";
  }
  setCellValue(newData, value) {
    let column = this;
    column.defaultSetCellValue(newData, value)
  }
}

export default App;
